apiRules:
- include:
    # Including the Plugins.CountlySDK namespace
    uidRegex: ^Plugins\.CountlySDK$
    type: Namespace
- include:
    # Including the Plugins.CountlySDK.* namespace
    uidRegex: ^Plugins\.CountlySDK\..+$
    type: Namespace
- include:
    # Including the Plugins.iBoxDB namespace
    uidRegex: ^Plugins\.iBoxDB$
    type: Namespace
- include:
    # Including the Notifications namespace
    uidRegex: ^Notifications$
    type: Namespace
- include:
    # Including the Notifications.* namespace
    uidRegex: ^Notifications\..+$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    # Exclude everything else
    uidRegex: .*
    type: Namespace